
project_id = "gfsfs ygledjtbqyuvarq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.ai-chat]
verify_jwt = false

[functions.ai-summarize]
verify_jwt = false
