// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfsfsygledjtbqyuvarq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmc2ZzeWdsZWRqdGJxeXV2YXJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDM0NzcsImV4cCI6MjA2Mjk3OTQ3N30.YQYmQUunUDeSQ0qrvv2n1rCycoBJk79DU8T5q5XH0yc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);